language: shell

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - shellcheck
  homebrew:
    packages:
      - shellcheck
    update: true

script:
  -	shellcheck --shell=bash sonoff-ota-flash.sh

